AWS_CONFIG="~/.aws/config"

[sso_sessions.kolja-cn]
sso_start_url = "https://xxx.awsapps.cn/start#replace-with-your-sso-url"
sso_region = "cn-northwest-1"
sso_registration_scopes = "sso:account:access"

[sso_sessions.kolja]
sso_start_url = "https://xxx.awsapps.cn/start#replace-with-your-sso-url"
sso_region = "ap-southeast-2"
sso_registration_scopes = "sso:account:access"
